services:
  trackerdb:
    build:
      context: ./Dockerfiles/db
    image: emacodes/trackerdb:latest
    container_name: trackerdb
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - trackerdbdata:/var/lib/postgresql/data
    networks:
      - backend  
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  trackerapp:
    build:
      context: .
      dockerfile: Dockerfiles/app/Dockerfile
    image: emacodes/trackerapp:latest
    container_name: trackerapp
    restart: unless-stopped
    env_file:
      - .env
    environment:
      GITHUB_REPO: "https://github.com/emaowusu/Travel-Tracker.git"
      GITHUB_BRANCH: "main"
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      NODE_ENV: ${NODE_ENV}
    ports:
      - "3000:3000"
    depends_on:
      - trackerdb
    networks:
      - backend

  nginx:
    build:
      context: ./Dockerfiles/web
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - trackerapp
    networks:
      - backend

volumes:
  trackerdbdata:

networks:
  backend:
    driver: bridge
