apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: trackerapp
        image: emacodes/trackerapp:v1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: tracker-secrets
                key: DB_PASSWORD
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: tracker-secrets
                key: DB_USER
          - name: DB_URL
            valueFrom:
              secretKeyRef:
                name: tracker-secrets
                key: DB_URL
          - name: SESSION_SECRET
            valueFrom:
              secretKeyRef:
                name: tracker-secrets
                key: SESSION_SECRET
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: tracker-config
                key: DB_HOST
          - name: DB_PORT
            valueFrom:
              configMapKeyRef:
                name: tracker-config
                key: DB_PORT
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: tracker-config
                key: DB_NAME
          - name: NODE_ENV
            valueFrom:
              configMapKeyRef:
                name: tracker-config
                key: NODE_ENV
          - name: SERVER_PORT
            valueFrom:
              configMapKeyRef:
                name: tracker-config
                key: SERVER_PORT
          - name: LOGIN_USERNAME
            valueFrom:
              configMapKeyRef:
                name: tracker-config
                key: LOGIN_USERNAME
          - name: LOGIN_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: tracker-config
                key: LOGIN_PASSWORD
      initContainers:
        - name: init-myservice
          image: busybox:1.28
          command: ['sh', '-c', "until nslookup trackerdb.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for mydb; sleep 2; done"]
        
        
