apiVersion: apps/v1
kind: Deployment
metadata:
  name: trackerdb-deploy
  labels:
    app: trackerdb
spec:
  selector:
    matchLabels:
      app: trackerdb
  replicas: 1
  template:
    metadata:
      labels:
        app: trackerdb
    spec:
      containers:
      - name: trackerdb
        image: emacodes/trackerdb:v1.0.0
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: trackerdb-data
        ports:
        - name: trackerdb-port
          containerPort: 5432
        env:
         - name: POSTGRES_USER
           valueFrom:
             secretKeyRef:
               name: tracker-secrets
               key: POSTGRES_USER
         - name: POSTGRES_PASSWORD
           valueFrom:
             secretKeyRef:
               name: tracker-secrets
               key: POSTGRES_PASSWORD
         - name: POSTGRES_DB
           valueFrom:
             secretKeyRef:
               name: tracker-secrets
               key: POSTGRES_DB
      volumes:
        - name: trackerdb-data
          persistentVolumeClaim:
            claimName: db-pv-claim

      initContainers:
        - name: busybox
          image: busybox:latest
          command: ["sh", "-c", "rm -rf /var/lib/postgresql/data/lost+found"]
          volumeMounts:
            - name: trackerdb-data
              mountPath: /var/lib/postgresql/data