apiVersion: v1
kind: Secret
metadata:
  name: tracker-secrets
type: Opaque
stringData:
  DB_USER: tracker_user
  DB_PASSWORD: StrongPassword123
  DB_URL: postgres://tracker_user:StrongPassword123@trackerdb:5432/world
  SESSION_SECRET: qwp0qGowMynepSHVW8NbRPgowEvItC4YhiNQijBrGTY=
  POSTGRES_PASSWORD: StrongPassword123
  POSTGRES_USER: tracker_user
  POSTGRES_DB: world

 
  
